load("//tools/build_defs/go:go_binary.bzl", "go_binary")

go_binary(
    name = "job",
    srcs = ["job.go"],
)

go_binary(
    name = "main",
    srcs = ["main.go"],
)

go_binary(
    name = "worker",
    srcs = ["worker.go"],
)
